// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLENGJZCcqwmjftfOtFwt-qcVCn9YXalI',
    appId: '1:7904411564:web:7d02793c82d57a2141c409',
    messagingSenderId: '7904411564',
    projectId: 'cmsc-23-demo',
    authDomain: 'cmsc-23-demo.firebaseapp.com',
    storageBucket: 'cmsc-23-demo.appspot.com',
    measurementId: 'G-58QXJLM7YK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw_YvNyqTlqZt6SxkKmNCvbu7X5IVnhRI',
    appId: '1:7904411564:android:9a28807677cd179c41c409',
    messagingSenderId: '7904411564',
    projectId: 'cmsc-23-demo',
    storageBucket: 'cmsc-23-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClY1bAU87mBYGDZChVICDbFbcqenEzpsQ',
    appId: '1:7904411564:ios:eb26143890aff1ec41c409',
    messagingSenderId: '7904411564',
    projectId: 'cmsc-23-demo',
    storageBucket: 'cmsc-23-demo.appspot.com',
    iosClientId: '7904411564-jvner65n3ftdd71vctodhr54rkbmp5va.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClY1bAU87mBYGDZChVICDbFbcqenEzpsQ',
    appId: '1:7904411564:ios:eb26143890aff1ec41c409',
    messagingSenderId: '7904411564',
    projectId: 'cmsc-23-demo',
    storageBucket: 'cmsc-23-demo.appspot.com',
    iosClientId: '7904411564-jvner65n3ftdd71vctodhr54rkbmp5va.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
