// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChIEzcmS4BYuUzI45-wg5MKK42jroRZ_o',
    appId: '1:59515119493:web:06060f777c1ae2cbe8c6ec',
    messagingSenderId: '59515119493',
    projectId: 'week08-firebase-robles',
    authDomain: 'week08-firebase-robles.firebaseapp.com',
    storageBucket: 'week08-firebase-robles.appspot.com',
    measurementId: 'G-P4BGWJ1DM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjBW88akIU6VKHG3UzD9Eg0UTJE1RGApI',
    appId: '1:59515119493:android:85e2ab5482ab09e5e8c6ec',
    messagingSenderId: '59515119493',
    projectId: 'week08-firebase-robles',
    storageBucket: 'week08-firebase-robles.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpjrp65ISXmWVhUu3gCK07qBHeoBWBTtU',
    appId: '1:59515119493:ios:c2394be48053e28ee8c6ec',
    messagingSenderId: '59515119493',
    projectId: 'week08-firebase-robles',
    storageBucket: 'week08-firebase-robles.appspot.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpjrp65ISXmWVhUu3gCK07qBHeoBWBTtU',
    appId: '1:59515119493:ios:c2394be48053e28ee8c6ec',
    messagingSenderId: '59515119493',
    projectId: 'week08-firebase-robles',
    storageBucket: 'week08-firebase-robles.appspot.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChIEzcmS4BYuUzI45-wg5MKK42jroRZ_o',
    appId: '1:59515119493:web:a6d09bcfdabdd311e8c6ec',
    messagingSenderId: '59515119493',
    projectId: 'week08-firebase-robles',
    authDomain: 'week08-firebase-robles.firebaseapp.com',
    storageBucket: 'week08-firebase-robles.appspot.com',
    measurementId: 'G-KY2SPR10FK',
  );
}
